events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;

    server {
        listen 80;
        server_name _;

        # Archivos estáticos del frontend
        root /usr/share/nginx/html;
        index index.html;

        # Proxy hacia el backend dentro del cluster
        location /api/ {
            proxy_pass http://backend-service:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Para SPA (si aplica)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Para retornar que pod responde a las peticiones y demostrar balanceo de carga
        location /whoami {
            return 200 "$hostname\n";
        }

    }
}
